(cl:in-package vn300-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME-VAL
          TIME
          WEEK-VAL
          WEEK
          STATUS-VAL
          STATUS
          RPY-VAL
          RPY
          LLA-VAL
          LLA
          NEDVEL-VAL
          NEDVEL
          YAWUNCERTAINTY-VAL
          YAWUNCERTAINTY
          PITCHUNCERTAINTY-VAL
          PITCHUNCERTAINTY
          ROLLUNCERTAINTY-VAL
          ROLLUNCERTAINTY
          POSUNCERTAINTY-VAL
          POSUNCERTAINTY
          VELUNCERTAINTY-VAL
          VELUNCERTAINTY
          SYNCINTIME-VAL
          SYNCINTIME
          SYNCINCOUNT-VAL
          SYNCINCOUNT
))