// Generated by gencpp from file vn300/ins.msg
// DO NOT EDIT!


#ifndef VN300_MESSAGE_INS_H
#define VN300_MESSAGE_INS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace vn300
{
template <class ContainerAllocator>
struct ins_
{
  typedef ins_<ContainerAllocator> Type;

  ins_()
    : header()
    , Time(0.0)
    , Week(0)
    , Status(0)
    , RPY()
    , LLA()
    , NedVel()
    , YawUncertainty(0.0)
    , PitchUncertainty(0.0)
    , RollUncertainty(0.0)
    , PosUncertainty(0.0)
    , VelUncertainty(0.0)
    , SyncInTime(0.0)
    , SyncInCount(0)  {
    }
  ins_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Time(0.0)
    , Week(0)
    , Status(0)
    , RPY(_alloc)
    , LLA(_alloc)
    , NedVel(_alloc)
    , YawUncertainty(0.0)
    , PitchUncertainty(0.0)
    , RollUncertainty(0.0)
    , PosUncertainty(0.0)
    , VelUncertainty(0.0)
    , SyncInTime(0.0)
    , SyncInCount(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _Time_type;
  _Time_type Time;

   typedef uint16_t _Week_type;
  _Week_type Week;

   typedef uint16_t _Status_type;
  _Status_type Status;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _RPY_type;
  _RPY_type RPY;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _LLA_type;
  _LLA_type LLA;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _NedVel_type;
  _NedVel_type NedVel;

   typedef float _YawUncertainty_type;
  _YawUncertainty_type YawUncertainty;

   typedef float _PitchUncertainty_type;
  _PitchUncertainty_type PitchUncertainty;

   typedef float _RollUncertainty_type;
  _RollUncertainty_type RollUncertainty;

   typedef float _PosUncertainty_type;
  _PosUncertainty_type PosUncertainty;

   typedef float _VelUncertainty_type;
  _VelUncertainty_type VelUncertainty;

   typedef double _SyncInTime_type;
  _SyncInTime_type SyncInTime;

   typedef uint32_t _SyncInCount_type;
  _SyncInCount_type SyncInCount;



  enum {
    STATUS_INSUFFICIENT_MOTION = 1u,
    STATUS_INS_OK = 2u,
    STATUS_GPS_FIX_OK = 4u,
    STATUS_SENSOR_ERROR_TIME = 8u,
    STATUS_SENSOR_ERROR_IMU = 16u,
    STATUS_SENSOR_ERROR_MAG = 32u,
    STATUS_SENSOR_ERROR_GPS = 64u,
  };


  typedef boost::shared_ptr< ::vn300::ins_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vn300::ins_<ContainerAllocator> const> ConstPtr;

}; // struct ins_

typedef ::vn300::ins_<std::allocator<void> > ins;

typedef boost::shared_ptr< ::vn300::ins > insPtr;
typedef boost::shared_ptr< ::vn300::ins const> insConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vn300::ins_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vn300::ins_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vn300

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vn300': ['/home/geo/autocone/src/vn300/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vn300::ins_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vn300::ins_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn300::ins_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn300::ins_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn300::ins_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn300::ins_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vn300::ins_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d73535fac7fc35ecd07989081b4b4e6";
  }

  static const char* value(const ::vn300::ins_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d73535fac7fc35eULL;
  static const uint64_t static_value2 = 0xcd07989081b4b4e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::vn300::ins_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vn300/ins";
  }

  static const char* value(const ::vn300::ins_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vn300::ins_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header       header\n\
float64               Time\n\
uint16                Week\n\
uint16                Status\n\
geometry_msgs/Vector3 RPY\n\
geometry_msgs/Vector3 LLA\n\
geometry_msgs/Vector3 NedVel\n\
float32               YawUncertainty\n\
float32               PitchUncertainty\n\
float32               RollUncertainty\n\
float32               PosUncertainty\n\
float32               VelUncertainty\n\
float64               SyncInTime\n\
uint32                SyncInCount\n\
\n\
uint16 STATUS_INSUFFICIENT_MOTION=1\n\
uint16 STATUS_INS_OK=2\n\
uint16 STATUS_GPS_FIX_OK=4\n\
uint16 STATUS_SENSOR_ERROR_TIME=8\n\
uint16 STATUS_SENSOR_ERROR_IMU=16\n\
uint16 STATUS_SENSOR_ERROR_MAG=32\n\
uint16 STATUS_SENSOR_ERROR_GPS=64\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::vn300::ins_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vn300::ins_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Time);
      stream.next(m.Week);
      stream.next(m.Status);
      stream.next(m.RPY);
      stream.next(m.LLA);
      stream.next(m.NedVel);
      stream.next(m.YawUncertainty);
      stream.next(m.PitchUncertainty);
      stream.next(m.RollUncertainty);
      stream.next(m.PosUncertainty);
      stream.next(m.VelUncertainty);
      stream.next(m.SyncInTime);
      stream.next(m.SyncInCount);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ins_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vn300::ins_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vn300::ins_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Time: ";
    Printer<double>::stream(s, indent + "  ", v.Time);
    s << indent << "Week: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Week);
    s << indent << "Status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Status);
    s << indent << "RPY: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.RPY);
    s << indent << "LLA: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.LLA);
    s << indent << "NedVel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.NedVel);
    s << indent << "YawUncertainty: ";
    Printer<float>::stream(s, indent + "  ", v.YawUncertainty);
    s << indent << "PitchUncertainty: ";
    Printer<float>::stream(s, indent + "  ", v.PitchUncertainty);
    s << indent << "RollUncertainty: ";
    Printer<float>::stream(s, indent + "  ", v.RollUncertainty);
    s << indent << "PosUncertainty: ";
    Printer<float>::stream(s, indent + "  ", v.PosUncertainty);
    s << indent << "VelUncertainty: ";
    Printer<float>::stream(s, indent + "  ", v.VelUncertainty);
    s << indent << "SyncInTime: ";
    Printer<double>::stream(s, indent + "  ", v.SyncInTime);
    s << indent << "SyncInCount: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.SyncInCount);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VN300_MESSAGE_INS_H
