// Generated by gencpp from file vn300/sensors.msg
// DO NOT EDIT!


#ifndef VN300_MESSAGE_SENSORS_H
#define VN300_MESSAGE_SENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace vn300
{
template <class ContainerAllocator>
struct sensors_
{
  typedef sensors_<ContainerAllocator> Type;

  sensors_()
    : header()
    , gps_time(0.0)
    , Mag()
    , Accel()
    , Gyro()
    , Temp(0.0)
    , Pressure(0.0)  {
    }
  sensors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gps_time(0.0)
    , Mag(_alloc)
    , Accel(_alloc)
    , Gyro(_alloc)
    , Temp(0.0)
    , Pressure(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _gps_time_type;
  _gps_time_type gps_time;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Mag_type;
  _Mag_type Mag;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Accel_type;
  _Accel_type Accel;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Gyro_type;
  _Gyro_type Gyro;

   typedef float _Temp_type;
  _Temp_type Temp;

   typedef float _Pressure_type;
  _Pressure_type Pressure;





  typedef boost::shared_ptr< ::vn300::sensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vn300::sensors_<ContainerAllocator> const> ConstPtr;

}; // struct sensors_

typedef ::vn300::sensors_<std::allocator<void> > sensors;

typedef boost::shared_ptr< ::vn300::sensors > sensorsPtr;
typedef boost::shared_ptr< ::vn300::sensors const> sensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vn300::sensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vn300::sensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vn300

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vn300': ['/home/geo/autocone/src/vn300/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vn300::sensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vn300::sensors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn300::sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn300::sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn300::sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn300::sensors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vn300::sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39b3da64afd92d016eb0b8e07688fc15";
  }

  static const char* value(const ::vn300::sensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39b3da64afd92d01ULL;
  static const uint64_t static_value2 = 0x6eb0b8e07688fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::vn300::sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vn300/sensors";
  }

  static const char* value(const ::vn300::sensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vn300::sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header       header\n\
float64		      gps_time\n\
geometry_msgs/Vector3 Mag \n\
geometry_msgs/Vector3 Accel\n\
geometry_msgs/Vector3 Gyro\n\
float32               Temp\n\
float32               Pressure\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::vn300::sensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vn300::sensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gps_time);
      stream.next(m.Mag);
      stream.next(m.Accel);
      stream.next(m.Gyro);
      stream.next(m.Temp);
      stream.next(m.Pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vn300::sensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vn300::sensors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gps_time: ";
    Printer<double>::stream(s, indent + "  ", v.gps_time);
    s << indent << "Mag: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Mag);
    s << indent << "Accel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Accel);
    s << indent << "Gyro: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Gyro);
    s << indent << "Temp: ";
    Printer<float>::stream(s, indent + "  ", v.Temp);
    s << indent << "Pressure: ";
    Printer<float>::stream(s, indent + "  ", v.Pressure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VN300_MESSAGE_SENSORS_H
